[package]
name = "qcms"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[dependencies]
libc = "0.2"
#core_arch = { path = "/Users/jrmuizel/src/stdarch/crates/core_arch" }


